name: Labeler

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      # All other permissions are set to none
      checks: write
      contents: read
      pull-requests: write
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          skip-delete: true
